# Generated by Django 3.1.4 on 2021-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('Business_Name', models.CharField(max_length=255)),
                ('Person_Name', models.CharField(max_length=255)),
                ('Contact_No', models.CharField(max_length=255)),
                ('Verify_Status', models.CharField(max_length=25)),
                ('TimeStamp', models.DateTimeField()),
            ],
        ),
    ]
